### ISSUE TITLE
是否可以考虑创建一个 DOCKER 镜像

### ISSUE THREAD

**Issue by foxes1998** [wlx65003/HZNUOJ#12]
因为正常安装总会出现各种问题，如果使用 docker 可以增加移植性

**Comment by wlx65003** [comment]
好的，我迟点写一个dockerfile，非常感谢你的建议。

**Comment by wlx65003** [comment]
Docker镜像已封装好，测试完毕，文档见首页README最下面，欢迎试用，再次感谢你的建议！
