### ISSUE TITLE
希望能够增加针对不同用户组的成员是否显示 sample input/output 的选项

### ISSUE THREAD

**Issue by foxes1998** [wlx65003/HZNUOJ#13]
加上这个选项应该能够减少投机取巧的情况出现。

**Comment by wlx65003** [comment]
不是特别理解你的需求？sample不就是给人看的吗？

**Comment by foxes1998** [comment]
因为我发现你们这上面使用的测试数据就是 sample input/output ，而我希望有样例输入输出作为展示，也有部分测试数据不展示出来

**Comment by wlx65003** [comment]
哦，我们这sample就是展示出来的，真正的数据需要手动上传。
你参考下这份出题手册，里面有讲怎么上传数据。
https://github.com/wlx65003/HZNUOJ#%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B
