### ISSUE TITLE
docker镜像里面无法上传测试数据

### ISSUE THREAD

**Issue by lixun2015** [wlx65003/HZNUOJ#14]
docker镜像里面无法上传测试数据，提示上传失败
添加题目的时候有添加sample data，但test data里面没看到in和out的文件
请问下怎么解决，是哪个文件夹权限的问题吗？

**Comment by wlx65003** [comment]
你好，感谢反馈，我确认下是否有这个问题。

**Comment by wlx65003** [comment]
你好，我试了下，并没有出现你的问题。数据是可以正常上传的。
能否提供更详细的复现问题的步骤？

**Comment by wlx65003** [comment]
我先关闭这个问题了，如果
